#!/bin/bash
#sudo easy_install pip
#sudo pip install virtualenv
virtualenv --no-site-packages ./python-env
chmod 755 ./python-env/bin/activate
source python-env/bin/activate
cd generate
pip install -r requirements.txt
python setup.py develop
